### ISSUE TITLE
Error: Could not find Chrome

### ISSUE THREAD

**Issue by mashegoindustries** [lewisdonovan/google-news-scraper#43]
Hi,

I seem to be getting this error everytime, my news scrapper cloud function runs.
Is anyone else experiencing this?

"An error occurred: Error: Could not find Chrome (ver. 122.0.6261.94). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /root/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:285:27)
    at ChromeLauncher.executablePath (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:196:25)
    at ChromeLauncher.computeLaunchArguments (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:89:37)
    at async ChromeLauncher.launch (/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:70:28)
    at async googleNewsScraper (/workspace/node_modules/google-news-scraper/index.js:29:19)
    at async generateGoogleNews (/workspace/lib/cron_jobs/google_news_scrapper/load_google_news_scraper.js:57:39)
    at async loadGoogleNewsScraperFunction (/workspace/lib/cron_jobs/google_news_scrapper/load_google_news_scraper.js:12:9)
    at async httpFunc (/workspace/node_modules/firebase-functions/lib/v2/providers/scheduler.js:67:13)"

**Comment by mashegoindustries** [comment]
Anyone running into this issue, using Firebase cloud functions Gen2,

I followed these instructions, and my issue was resolved
https://github.com/puppeteer/puppeteer/issues/9128#issuecomment-1809533112
